config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    resources :relationships, only: [:create, :destroy]
    resources :recommends, only: :index
  end

  resources :recommends, only: [:new, :create, :update]
  namespace :recommends do
    resources :users, only: :index
    resources :books, only: :index
  end

  resources :books do
    get :search, on: :collection
    resource :favorites, only: [:create, :destroy]
    resource :reviews, only: [:create, :edit, :update, :destroy]
  end

  resources :authors, only: [:index, :show]

  resources :notifications, only: :index

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @ranking_books = Book.reorder(recomme_evaluation_point: "DESC").limit(4)
    @ranking_users = User.reorder(recomme_point: "DESC").limit(4)
  end

  def about
  end
end

app/views/static_pages/home.html.slim
- provide(:title, "ホーム")
- breadcrumb :root
.container

  == breadcrumbs separator: " &rsaquo; "

  .row
    .col-xl-9#top-page
      .main-area
        .row
          .col-md-7
            .main-message-area
              h1.title RecommeBooks
              p.sub-title レコメブックス
              p.main-message 本をおすすめしよう
              p.sub-message ユーザー同士で本をレコメンドするサービスです。
              p.sub-message あなたの「座右の書」を、あの人に。
              .recomme-area
                a ＞＞
                = link_to new_recommend_path, class: "btn btn-home", id: "main-reco" do
                  i.fas.fa-hand-holding-heart
                  span 早速レコメンドしてみる
          .col-md-5
            = image_tag 'main-logo-6.png', size: '250x250', class: "logo-mark"
      .explanation-area
        p.title レコメブックスとは？
        p.sub-title レコメブックスは本の投稿・レビュー共有型のSNSサービスです。
        p.sub-title 他のユーザーへの本のレコメンドと、レコメンドに対する評価を行うことができます。
        .items
          .container
            .row
              .col-md-6
                .item.left
                  p.item-titol 読んだ本を投稿しよう
                  .image
                    = image_tag 'booklogo2white.png', size: '80x80', class: "logo book-logo"
                  p.item-sub あなたの感想と共に本を投稿しよう
                  p.item-sub すでに投稿されている本にはレビューの投稿ができます
                  = link_to search_books_path, class: "btn btn-home" do
                    i.fas.fa-book
                    span 本を投稿してみる
              .col-md-6
                .item.right
                  p.item-titol 気になるユーザーをフォローしよう
                  .image
                    = image_tag 'follow-logo.png', size: '80x80', class: "logo follow-logo"
                  p.item-sub あなたのタイムラインでフォローしたユーザーの
                  p.item-sub 投稿を確認できます                  
                  = link_to users_path, class: "btn btn-home" do
                    i.fas.fa-user
                    span ユーザーの一覧へ
            .row
              .col-md-6
                .item.left
                  p.item-titol 本をレコメンドしよう
                  .image
                    = image_tag 'recommend-logo.png', size: '80x80', class: "logo recommend-logo"
                  p.item-sub ユーザーのプロフィールや投稿を確認して
                  p.item-sub そのユーザーにぴったりな一冊をレコメンドしてみよう                  
                  = link_to new_recommend_path, class: "btn btn-home" do
                    i.fas.fa-hand-holding-heart
                    span レコメンドしてみる
              .col-md-6
                .item.right
                  p.item-titol レコメポイントを貯めよう
                  .image
                    = image_tag 'point-logo.png', size: '80x80', class: "logo point-logo"
                  p.item-sub レコメンドした相手がその本を「面白かった！」と
                  p.item-sub 評価したら、あなたのレコメポイント(RP)が貯まります
                  - if logged_in?
                    = link_to user_recommends_path(current_user.id), class: "btn btn-home" do
                      i.fas.fa-list-ul
                      span レコメンド状況を確認する
                  - else
                    = link_to login_path, class: "btn btn-home" do
                      i.fas.fa-list-ul
                      span レコメンド状況を確認する
      .book-ranking-area
        p.title 本のレコメ評価ポイント(REP)ランキング
        button class="whatrep1 btn btn-primary" type="button"
          i.fas.fa-question-circle
          a レコメ評価ポイント(REP)とは？
        div class = 'target1 is-hidden' target = "_blank"
          a 本のレコメンドの評価が「面白かった！」であった場合、その本に加算されるポイントです。
        - if @ranking_books.present?
          .row
            - r = 1 
            - prev = @ranking_books.first.recomme_evaluation_point
            - @ranking_books.each_with_index do |book, i|
              - if book.recomme_evaluation_point == prev
                - r = r
              - else
                - r = i + 1
                - prev = book.recomme_evaluation_point
              .col-lg-3
                .book-thumb
                  div id = "thumb-book-raning" class = "ver-#{r}"
                    - if r != 4
                      i.fas.fa-crown
                    a.rank #{r}位
                    a.book-rep  #{book.recomme_evaluation_point}REP
                  #book-thumb-image
                    = link_to book_path(book)
                      - if book.image?
                        = image_tag book.image, class: "book-image", width: '140px'
                      - else
                        =image_tag 'booklogo.jpg', size: '120x135', class: "book-image"
                  #book-thumb-overview
                    .thumb-book-title
                      = link_to book.title.truncate(10), book_path(book), class: "text"
                    .thumb-book-author
                      = link_to book.author.name.truncate(10), author_path(book.author), class: "text"
                      a 著
      .user-ranking-area
        p.title ユーザーのレコメポイント(RP)ランキング
        button class="whatrep2 btn btn-primary" type="button"
          i.fas.fa-question-circle
          a レコメポイント(RP)とは？
        div class = 'target2 is-hidden' target = "_blank"
          a レコメンドの評価が「面白かった！」であった場合、レコメンドしたユーザーに加算されるポイントです。
        - if @ranking_users.present?
          .row
            - r = 1 
            - prev = @ranking_users.first.recomme_point
            - @ranking_users.each_with_index do |user, i|
              - if user.recomme_point == prev
                - r = r
              - else
                - r = i + 1
                - prev = user.recomme_point
              .col-lg-3
                .user-thumb
                  div id = "thumb-user-raning" class = "ver-#{r}"
                    - if r != 4
                      i.fas.fa-crown
                    a.rank #{r}位
                    a.user-rep  #{user.recomme_point}RP
                  #thumb-user-title
                    a 「#{user.title.name}」
                  #user-thumb-image
                    = link_to user_path(user)
                      - if user.image?
                        = image_tag user.image_url(:thumb2), class: "user-image"
                      - else
                        =image_tag 'userlogo2.png', size: '120x135', class: "user-image"
                  #user-thumb-overview
                    .thumb-user-name
                      = link_to user.name.truncate(10), user_path(user), class: "text"
        
    .col-xl-3
      = render 'shared/right_side' 