config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    resources :relationships, only: [:create, :destroy]
    resources :recommends, only: :index
  end

  resources :recommends, only: [:new, :create, :update]
  namespace :recommends do
    resources :users, only: :index
    resources :books, only: :index
  end

  resources :books do
    get :search, on: :collection
    resource :favorites, only: [:create, :destroy]
    resource :reviews, only: [:create, :edit, :update, :destroy]
  end

  resources :authors, only: [:index, :show]

  resources :notifications, only: :index

end

app/models/user.rb
class User < ApplicationRecord
    belongs_to :title

    has_many :books

    has_many :favorites, dependent: :destroy
    has_many :favorite_books, through: :favorites, source: :book

    has_many :reviews, dependent: :destroy

    has_many :active_relationships, class_name:  "Relationship",
                                    foreign_key: "follower_id",
                                    dependent:   :destroy
    has_many :following, through: :active_relationships, source: :followed
    has_many :passive_relationships, class_name:  "Relationship",
                                     foreign_key: "followed_id",
                                     dependent:   :destroy
    has_many :followers, through: :passive_relationships, source: :follower

    has_many :active_recommends, class_name:  "Recommend",
                                    foreign_key: "recommender_id",
                                    dependent:   :destroy
    has_many :recommending, through: :active_recommends, source: :recommended
    has_many :passive_recommends, class_name:  "Recommend",
                                     foreign_key: "recommended_id",
                                     dependent:   :destroy

    has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
    has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

    has_many :user_genres, dependent: :destroy
    has_many :genres, through: :user_genres

    before_save { self.email = email.downcase }
    validates :name, presence: true, length: { maximum: 45 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, uniqueness: { case_sensitive: false }, 
                      length: { maximum: 255 },
                      format: { with: VALID_EMAIL_REGEX }
    validates :favorite_genre, length: { maximum: 45 }
    validates :profile, length: { maximum: 255 }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
    
    mount_uploader :image, ImageUploader

    def time_line_feed_books
        # Book.where(user_id: Relationship.where(follower: self).select(:followed_id)).or(books)
        Book.where(user: following).or(books)
    end

    def time_line_feed_reviews
        # Review.where(user_id: Relationship.where(follower: self).select(:followed_id)).or(reviews)
        Review.where(user: following).or(reviews)
    end

    def follow(other_user)
        following << other_user
    end

    def unfollow(other_user)
        active_relationships.find_by(followed: other_user).destroy
    end

    def following?(other_user)
        following.include?(other_user)
    end

    def save_genres(tag_ids)
        current_tag_ids = self.genre_ids unless self.genres.nil?
        new_tag_ids = tag_ids - current_tag_ids
        user_genres.where.not(genre_id: tag_ids).delete_all
        self.genres << Genre.find(new_tag_ids)
    end

    def create_notification_follow!(current_user)
        temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ",current_user.id, id, 'follow'])
        if temp.blank?
            notification = current_user.active_notifications.new(visited_id: id, action: 'follow')
            notification.save! if notification.valid?
        end
    end

    def update_title_or_not
        if self.recomme_point == 5 || self.recomme_point == 15
            self.increment!(:title_id, 1)
        end
    end

end

app/controllers/recommends/users_controller.rb
class Recommends::UsersController < ApplicationController

    def index
        @q = User.ransack(params[:q])
        @users = @q.result(distinct: true).order(created_at: "DESC").paginate(page: params[:page])
        @book_id = params[:book_id] || params.dig(:q, :book_id)
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :logged_in_user, only: [:edit, :update, :destroy]
    before_action :correct_user, only: [:edit, :update]
    before_action :admin_user,     only: :destroy
    before_action :set_genre,     only: [:edit, :update]
    require 'will_paginate/array'

    def index
        @q = User.ransack(params[:q])
        @users = @q.result(distinct: true).order(created_at: "DESC").paginate(page: params[:page])
    end
    
    def show
        @user = User.find_by(id: params[:id])
        @post_feed_books = @user.books.paginate(page: params[:page])
        @post_feed_reviews = @user.reviews.paginate(page: params[:page])
        @following = @user.following.order("relationships.created_at DESC").paginate(page: params[:page])
        @followers = @user.followers.order("relationships.created_at DESC").paginate(page: params[:page])
        if logged_in? && current_user?(@user)
            @time_line_feed_books = current_user.time_line_feed_books.paginate(page: params[:page]) 
            @time_line_feed_reviews = current_user.time_line_feed_reviews.paginate(page: params[:page]) 
            @favorite_books = @user.favorites.order(created_at: :desc).map(&:book).paginate(page: params[:page])
        end
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            log_in @user
            flash[:primary] = "ユーザー登録が完了しました。レコメブックスへようこそ！"
            redirect_to @user
        else
            render 'new'
        end
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        if @user.update_attributes(user_params)
            unless params[:user][:genre_ids].nil?
                @user.save_genres(params[:user][:genre_ids].map(&:to_i)) #配列にstring型でidが格納されているため、integer型に変換して配列化
            else
                @user.save_genres([])
            end
            flash[:primary] = "プロフィールを更新しました"
            redirect_to @user
        else
            render 'edit'
        end
    end

    def destroy
        User.find(params[:id]).destroy
        flash[:primary] = "削除しました"
        redirect_to users_url
    end

    private

        def user_params
            params.require(:user).permit(:name, :email, :password, :password_confirmation,
                                         :favorite_genre, :profile, :image)
        end

        def correct_user
            @user = User.find(params[:id])
            unless current_user?(@user)
                flash[:danger] = "無効な処理です"
                redirect_to(root_url)                      
            end
        end

        def set_genre
            #@genre = { "1": "文学・小説", "2": "社会・ビジネス", "3": "趣味・実用", "4": "芸術・教養・エンタメ",
            #           "5": "旅行・地図", "6": "暮らし・健康", "7": "図鑑・百科事典", "8": "こども", "9": "コミック" } 
            @genre = {}
            d = 0
            Genre.all.each do |genre|
                if genre.division != d
                    @genre[genre.division.to_s] = genre.name
                    d += 1
                end
            end
        end

end

app/helpers/recommends/users_helper.rb
module Recommends::UsersHelper
end

app/views/users/_follow_form.html.slim
#user-follow-button
  - if current_user.following?(user)
    = form_with model: [ current_user, current_user.active_relationships.find_by(followed_id: user.id) ],
                html: {method: :delete} do |f|
      .form-group
        = f.submit "フォロー解除", class: "form-control btn btn-cancell"
  - else
    = form_with model: [ current_user, current_user.active_relationships.build ] do |f|
      .form-group
        = f.hidden_field :followed_id, :value => user.id
        = button_tag type: 'submit', class: 'form-control btn btn-primary' do
          i.fas.fa-user
          span フォローする
         

app/views/users/_show_mypage.html.slim
- provide(:title, "マイページ")
- breadcrumb :my_page, @user
.container
  == breadcrumbs separator:  ">" , class: "breadcrumb"

  .row
    .col-xl-9#usershow
      .row.user-show-top
        .col-lg-12.user-name
          = @user.name
      .row
        .col-lg-4.user-image-btn
          - if @user.image?
            =image_tag @user.image_url(:thumb1), class: "user-image"
          - else
            =image_tag 'userlogo2.png', size: '240x260', class: "user-image"
          - if @user.email != 'testa@test.com' && @user.email != 'testb@test.com'
            = link_to edit_user_path(current_user), class: "btn btn-primary", id: "user-edit-button" do
              i.far.fa-edit
              span プロフィールの編集
          = link_to search_books_path, class: "btn btn-primary", id: "book-post-button" do
            i.fas.fa-book
            span 本を投稿
          = link_to user_recommends_path(@user.id), class: "btn btn-primary", id: "user-recomme-button" do
            i.fas.fa-list-ul
            span レコメンド状況
        .col-lg-8.user-overview
          p.user-title  称号「#{@user.title.name}」
          button class="whatrep5 btn btn-primary" type="button"
            i.fas.fa-question-circle
            a 称号とは？
          div class = 'target5 is-hidden' target = "_blank"
            a レコメポイント数に応じて称号が付与されます。まずは5レコメポイント貯めると新たな称号が・・・
          p.user-recomme-point  #{@user.recomme_point}レコメポイント
          - @user.recomme_point.times do
            = image_tag 'main-logo-9.png', size: '50x50', class: "logo-mark"
          button class="whatrep4 btn btn-primary" type="button"
            i.fas.fa-question-circle
            a レコメポイント(RP)とは？
          div class = 'target4 is-hidden' target = "_blank"
            a レコメンドの評価が「面白かった！」であった場合、レコメンドしたユーザーに加算されるポイントです。
          .user-profile-favorirte-genre
            - if @user.profile?
              p.heading 自己紹介
              = simple_format(@user.profile, class: "user-profile table-bordered")
            - if @user.favorite_genre? || @user.genres.present?
              p.heading 好きなジャンル・本
              - @user.genres.each do |genre|
                .genre-tag-mark.bg-warning
                  a.fa.fa-tag
                  = link_to genre.name, books_path(genre_id: genre.id), id: "genre-tag-text"
            - if @user.favorite_genre?
              = simple_format(@user.favorite_genre, class: "user-favorirte-genre table-bordered")
          ul.nav.nav-tabs.justify-content-center role = "tablist"         
            li.nav-item
              a.nav-link.active#time-line-tab data-toggle="tab" href="#time-line" role="tab" aria-controls="time-line" aria-selected="true"
                p タイムライン  
            li.nav-item
              a.nav-link#fav-tab data-toggle="tab" href="#fav" role="tab" aria-controls="fav" aria-selected="false"
                p つんどく本
            li.nav-item
              a.nav-link#post-tab data-toggle="tab" href="#post" role="tab" aria-controls="post" aria-selected="true"
                p 投稿
            li.nav-item
              a.nav-link#follow-tab data-toggle="tab" href="#follow" role="tab" aria-controls="follow" aria-selected="false"
                p フォロー
            li.nav-item
              a.nav-link#follower-tab data-toggle="tab" href="#follower" role="tab" aria-controls="follower" aria-selected="false"
                p フォロワー
          .tab-content
            .tab-pane.fade.show.active#time-line role="tabpanel" aria-labelledby="time-line-tab"
              ul.nav.nav-tabs.justify-content-center role = "tablist" 
                li.nav-item.under-nav
                  a.nav-link.active#time-line-books-tab data-toggle="tab" href="#time-line-books" role="tab" aria-controls="time-line-books" aria-selected="true"
                    p 本
                li.nav-item.under-nav
                  a.nav-link#time-line-comments-tab data-toggle="tab" href="#time-line-comments" role="tab" aria-controls="time-line-comments" aria-selected="true"
                    p レビュー
              .tab-content
                .tab-pane.fade.show.active#time-line-books role="tabpanel" aria-labelledby="time-line-books-tab"
                  - if @time_line_feed_books.present?
                    - @time_line_feed_books.each do |book|
                      = render 'books/book_thumb_tl', { book: book }
                    = will_paginate(@time_line_feed_books, renderer: WillPaginate::ActionView::BootstrapLinkRenderer)
                  - else
                    p 表示する投稿がありません
                .tab-pane.fade.show#time-line-comments role="tabpanel" aria-labelledby="time-line-comments-tab"
                  - if @time_line_feed_reviews.present?
                    - @time_line_feed_reviews.each do |review|
                      = render 'reviews/review_thumb_tl', { review: review }
                    = will_paginate(@time_line_feed_reviews, renderer: WillPaginate::ActionView::BootstrapLinkRenderer)
                  - else
                    p 表示する投稿がありません
            .tab-pane.fade#fav role="tabpanel" aria-labelledby="fav-tab"
              - if @favorite_books.any?
                  - @favorite_books.each do |book|
                    = render 'books/book_thumb_fav', { book: book }
                  = will_paginate(@favorite_books, renderer: WillPaginate::ActionView::BootstrapLinkRenderer)
              - else
                  p つんどく本がありません
            .tab-pane.fade.show#post role="tabpanel" aria-labelledby="post-tab"
              ul.nav.nav-tabs.justify-content-center role = "tablist" 
                li.nav-item.under-nav
                  a.nav-link.active#post-books-tab data-toggle="tab" href="#post-books" role="tab" aria-controls="post-books" aria-selected="true"
                    p 本
                li.nav-item.under-nav
                  a.nav-link#post-comments-tab data-toggle="tab" href="#post-comments" role="tab" aria-controls="post-comments" aria-selected="true"
                    p レビュー
              .tab-content
                .tab-pane.fade.show.active#post-books role="tabpanel" aria-labelledby="post-books-tab"
                  - if @post_feed_books.any?
                    - @post_feed_books.each do |book|
                      = render 'books/book_thumb_post', { book: book }
                    = will_paginate(@post_feed_books, renderer: WillPaginate::ActionView::BootstrapLinkRenderer)
                  - else
                    p 表示する投稿がありません
                .tab-pane.fade.show#post-comments role="tabpanel" aria-labelledby="post-comments-tab"
                  - if @post_feed_reviews.any?
                    - @post_feed_reviews.each do |review|
                      = render 'reviews/review_thumb_post', { review: review }
                    = will_paginate(@post_feed_reviews, renderer: WillPaginate::ActionView::BootstrapLinkRenderer)
                  - else
                    p 表示する投稿がありません
            .tab-pane.fade#follow role="tabpanel" aria-labelledby="follow-tab"
              - if @following.any?
                - @following.each do |user|
                  = render 'users/user_following', { user: user }
                = will_paginate(@following, renderer: WillPaginate::ActionView::BootstrapLinkRenderer)
              - else
                p フォローしているユーザーがいません
            .tab-pane.fade#follower role="tabpanel" aria-labelledby="follower-tab"
              - if @followers.any?
                - @followers.each do |user|
                  = render 'users/user_followers', { user: user }
                = will_paginate(@followers, renderer: WillPaginate::ActionView::BootstrapLinkRenderer)
              - else
                p フォロワーがいません
              
    .col-xl-3
      = render 'shared/right_side_for_mypage'        

app/views/users/_show_userpage.html.slim
- provide(:title, "ユーザー詳細")
- breadcrumb :user, @user
.container
  == breadcrumbs separator:  ">" , class: "breadcrumb"
  
  .row
    .col-xl-9#usershow
      .row.user-show-top
        .col-lg-12.user-name
          = @user.name
      .row
        .col-lg-4.user-image-btn
          - if @user.image?
            =image_tag @user.image_url(:thumb1), class: "user-image"
          - else
            =image_tag 'userlogo2.png', size: '240x260', class: "user-image"
          - if logged_in?
            div id = "follow-button-show-#{@user.id}"
              = render 'follow_form', user: @user
            = link_to new_recommend_path(user_id: @user.id), class: "btn btn-primary", id: "user-recomme-button" do
              i.fas.fa-hand-holding-heart
              span レコメンドする
            = link_to user_recommends_path(@user.id), class: "btn btn-primary", id: "user-recomme-button" do
              i.fas.fa-list-ul
              span レコメンド状況
        .col-lg-8.user-overview
          p.user-title  称号「#{@user.title.name}」
          button class="whatrep7 btn btn-primary" type="button"
            i.fas.fa-question-circle
            a 称号とは？
          div class = 'target7 is-hidden' target = "_blank"
            a レコメポイント数に応じて称号が付与されます。まずは5レコメポイント貯めると新たな称号が・・・
          p.user-recomme-point  #{@user.recomme_point}レコメポイント
          - @user.recomme_point.times do
            = image_tag 'main-logo-9.png', size: '50x50', class: "logo-mark"
          button class="whatrep6 btn btn-primary" type="button"
            i.fas.fa-question-circle
            a レコメポイント(RP)とは？
          div class = 'target6 is-hidden' target = "_blank"
            a レコメンドの評価が「面白かった！」であった場合、レコメンドしたユーザーに加算されるポイントです。
          .user-profile-favorirte-genre
            - if @user.profile?
              p.heading 自己紹介
              = simple_format(@user.profile, class: "user-profile table-bordered")
            - if @user.favorite_genre? || @user.genres.present?
              p.heading 好きなジャンル・本
              - @user.genres.each do |genre|
                .genre-tag-mark.bg-warning
                  a.fa.fa-tag
                  = link_to genre.name, books_path(genre_id: genre.id), id: "genre-tag-text"
            - if @user.favorite_genre?
              = simple_format(@user.favorite_genre, class: "user-favorirte-genre table-bordered")
          ul.nav.nav-tabs.justify-content-center role = "tablist" 
            li.nav-item
              a.nav-link.active#post-tab data-toggle="tab" href="#post" role="tab" aria-controls="post" aria-selected="true"
                p 投稿
            li.nav-item
              a.nav-link#follow-tab data-toggle="tab" href="#follow" role="tab" aria-controls="follow" aria-selected="false"
                p フォロー
            li.nav-item
              a.nav-link#follower-tab data-toggle="tab" href="#follower" role="tab" aria-controls="follower" aria-selected="false"
                p フォロワー
          .tab-content
            .tab-pane.fade.show.active#post role="tabpanel" aria-labelledby="post-tab"
              ul.nav.nav-tabs.justify-content-center role = "tablist" 
                li.nav-item.under-nav
                  a.nav-link.active#post-books-tab data-toggle="tab" href="#post-books" role="tab" aria-controls="post-books" aria-selected="true"
                    p 本
                li.nav-item.under-nav
                  a.nav-link#post-comments-tab data-toggle="tab" href="#post-comments" role="tab" aria-controls="post-comments" aria-selected="true"
                    p レビュー
              .tab-content
                .tab-pane.fade.show.active#post-books role="tabpanel" aria-labelledby="post-books-tab"
                  - if @post_feed_books.any?
                    - @post_feed_books.each do |book|
                      = render 'books/book_thumb_tl', { book: book }
                    = will_paginate(@post_feed_books, renderer: WillPaginate::ActionView::BootstrapLinkRenderer)
                  - else
                    p 表示する投稿がありません
                .tab-pane.fade.show#post-comments role="tabpanel" aria-labelledby="post-comments-tab"
                  - if @post_feed_reviews.any?
                    - @post_feed_reviews.each do |review|
                      = render 'reviews/review_thumb_tl', { review: review }
                    = will_paginate(@post_feed_reviews, renderer: WillPaginate::ActionView::BootstrapLinkRenderer)
                  - else
                    p 表示する投稿がありません
            .tab-pane.fade#follow role="tabpanel" aria-labelledby="follow-tab"
              - if @following.any?
                - @following.each do |user|
                  = render 'users/user_following', { user: user }
                = will_paginate(@following, renderer: WillPaginate::ActionView::BootstrapLinkRenderer)
              - else
                p フォローしているユーザーがいません
            .tab-pane.fade#follower role="tabpanel" aria-labelledby="follower-tab"
              - if @followers.any?
                - @followers.each do |user|
                  = render 'users/user_followers', { user: user }
                = will_paginate(@followers, renderer: WillPaginate::ActionView::BootstrapLinkRenderer)
              - else
                p フォロワーがいません
              
    .col-xl-3
      = render 'shared/right_side'        

app/views/users/_user.html.slim
.users-thumb
  #users-thumb-image
    = link_to user_path(user)
      - if user.image?
        = image_tag user.image_url(:thumb2), class: "user-image"
      - else
        =image_tag 'userlogo2.png', size: '120x135', class: "user-image"
  #users-thumb-overview
    .thumb-user-name
      = link_to user_path(user)
        = user.name
      a.thumb-recomme-point #{user.recomme_point}RP「#{user.title.name}」
      - if !current_user.nil? && current_user.admin? && !current_user?(user)
        = link_to '削除', user, method: :delete, data: { confirm: '削除しますか？' }, id: "delete-nallow"
    = simple_format(user.favorite_genre, class: "thumb-user-favorite-genre d-none d-sm-block")
    - if logged_in? && !current_user?(user)
      .thumb-follow-recomme
        = link_to new_recommend_path(user_id: user.id), class: "btn btn-primary", id: "thmb-recomme-btn" do
          i.fas.fa-hand-holding-heart
          span レコメンドする
        div id = "follow-button-thumb-#{user.id}" class= "follow-btn"
          = render 'follow_form', user: user

app/views/users/_user_followers.html.slim
.users-thumb
  #users-thumb-image
    = link_to user_path(user)
      - if user.image?
        = image_tag user.image_url(:thumb2), class: "user-image"
      - else
        =image_tag 'userlogo2.png', size: '120x135', class: "user-image"
  #users-thumb-overview
    .thumb-user-name
      = link_to user_path(user)
        = user.name
      a.thumb-recomme-point #{user.recomme_point}RP(レコメニスト)
      - if !current_user.nil? && current_user.admin? && !current_user?(user)
        = link_to '削除', user, method: :delete, data: { confirm: '削除しますか？' }, id: "delete-nallow"
    = simple_format(user.favorite_genre, class: "thumb-user-favorite-genre d-none d-sm-block")
    - if logged_in? && !current_user?(user)
      .thumb-follow-recomme
        = link_to new_recommend_path(user_id: user.id), class: "btn btn-primary", id: "thmb-recomme-btn" do
          i.fas.fa-hand-holding-heart
          span レコメンドする
        div id = "follow-button-thumb-followers-#{user.id}" class= "follow-btn"
          = render 'follow_form', user: user

app/views/users/_user_following.html.slim
.users-thumb
  #users-thumb-image
    = link_to user_path(user)
      - if user.image?
        = image_tag user.image_url(:thumb2), class: "user-image"
      - else
        =image_tag 'userlogo2.png', size: '120x135', class: "user-image"
  #users-thumb-overview
    .thumb-user-name
      = link_to user_path(user)
        = user.name
      a.thumb-recomme-point #{user.recomme_point}RP(レコメニスト)
      - if !current_user.nil? && current_user.admin? && !current_user?(user)
        = link_to '削除', user, method: :delete, data: { confirm: '削除しますか？' }, id: "delete-nallow"
    = simple_format(user.favorite_genre, class: "thumb-user-favorite-genre d-none d-sm-block")
    - if logged_in? && !current_user?(user)
      .thumb-follow-recomme
        = link_to new_recommend_path(user_id: user.id), class: "btn btn-primary", id: "thmb-recomme-btn" do
          i.fas.fa-hand-holding-heart
          span レコメンドする
        div id = "follow-button-thumb-following-#{user.id}" class= "follow-btn"
          = render 'follow_form', user: user

app/views/users/_user_reco_choose.html.slim
.users-reco-choose
  #users-thumb-image
    - if user.image?
      = image_tag user.image_url(:thumb2), class: "user-image"
    - else
      =image_tag 'userlogo2.png', size: '120x135', class: "user-image"
  #users-thumb-overview
    .thumb-user-name
      = user.name
      a.thumb-recomme-point #{user.recomme_point}RP(レコメニスト)
    = simple_format(user.favorite_genre, class: "thumb-user-favorite-genre d-none d-sm-block")
    .thumb-follow-recomme
      - if !current_user?(user)
        - if params[:book_id]
          = link_to new_recommend_path(user_id: user.id, book_id: params[:book_id]), class: "btn btn-primary", id: "thmb-recomme-btn" do
            i.fas.fa-hand-holding-heart
            span レコメンドする
        - elsif params[:q]
          = link_to new_recommend_path(user_id: user.id, book_id: params[:q][:book_id]), class: "btn btn-primary", id: "thmb-recomme-btn" do
            i.fas.fa-hand-holding-heart
            span レコメンドする
        - else
          = link_to new_recommend_path(user_id: user.id), class: "btn btn-primary", id: "thmb-recomme-btn" do
            i.fas.fa-hand-holding-heart
            span レコメンドする

app/views/users/index.html.slim
- provide(:title, "ユーザー一覧")
- breadcrumb :users
.container#userindex
  
  == breadcrumbs separator:  ">" , class: "breadcrumb"

  h2  ユーザー一覧

  = search_form_for @q do |f|
    .form-group.search-form
      = f.search_field :name_cont, class: 'form-control input-area', id: "user-index-search", placeholder: "ユーザー名で検索"
      = f.submit "検索", class: "btn btn-primary"
  
  = will_paginate(@users, renderer: WillPaginate::ActionView::BootstrapLinkRenderer)
  .row.users
    - if @users.present?
      - @users.each do |user|
        .col-xl-6 
          = render 'users/user', { user: user }
    - else
      p.no-user-message 表示するユーザーがいません
  = will_paginate(@users, renderer: WillPaginate::ActionView::BootstrapLinkRenderer)

app/views/users/new.html.slim
- provide(:title, "新規登録")
- breadcrumb :user_new
.container
  == breadcrumbs separator:  ">" , class: "breadcrumb"
  
  .row
    .col-xl-9#users_new
      .row
        .offset-md-1.col-md-10.offset-lg-2.col-lg-8
          .card
            .card-header
              h4.text-center 新規登録
            .card-body
              = form_with model: @user, local: true do |f|
                = render 'shared/error_messages', object: f.object
    
                .form-group
                  = f.label :name, 'ユーザー名'
                  = f.text_field :name, class: 'form-control'
                .form-group
                  = f.label :email, 'メールアドレス'
                  = f.email_field :email, class: 'form-control'
                .form-group
                  = f.label :password, 'パスワード'
                  = f.password_field :password, class: 'form-control'
                .form-group
                  = f.label :password_confirmation, 'パスワードの確認'
                  = f.password_field :password_confirmation, class: 'form-control' 
                        
                  = button_tag type: 'submit', class: 'btn-block btn btn-primary' do
                    i.fas.fa-user-plus
                    span 登録
    
                p.guidance-login  ユーザー登録されてる方は#{link_to 'こちらからログイン', login_path}してください
    .col-xl-3
      = render 'shared/right_side_for_login_signup'  
    

app/views/users/show.html.slim
- if logged_in? && current_user?(@user)
  = render 'show_mypage'
- else
  = render 'show_userpage'