config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    resources :relationships, only: [:create, :destroy]
    resources :recommends, only: :index
  end

  resources :recommends, only: [:new, :create, :update]
  namespace :recommends do
    resources :users, only: :index
    resources :books, only: :index
  end

  resources :books do
    get :search, on: :collection
    resource :favorites, only: [:create, :destroy]
    resource :reviews, only: [:create, :edit, :update, :destroy]
  end

  resources :authors, only: [:index, :show]

  resources :notifications, only: :index

end

app/views/shared/_error_messages.html.slim
- if object.errors.any?
  #error_explanation
    ul
      - object.errors.full_messages.each do |msg|
        li = msg

app/views/shared/_flash_messages.html.slim
-flash.each do |message_type, message|
        =content_tag :div, class: "alert alert-#{message_type} alert-dismissible" 
          button.close[data-dismiss="alert" type="button" aria-label="Close"]
            span[aria-hidden="true"] &times;
          = message

app/views/shared/_login_signup.html.slim
.card
  .card-header 新規登録はこちら
  .card-body
    .login
      = link_to signup_path, class: "btn btn-primary", id: "side-login" do
        i.fas.fa-user-plus
        span 新規登録
    p.signup アカウントをお持ちの方は
    a
      = link_to "ログイン", login_path
    a してください

app/views/shared/_my_user_info.html.slim
#user-image-name
  .row
    .col-sm-4
      = link_to user_path(user), class: "user-image-space"
        - if user.image?
          = image_tag user.image_url(:thumb2), size: '60x60', class: "user-image"
        - else
          = image_tag 'userlogo2.png', size: '60x60', class: "user-image"
    .col-sm-8
      = link_to user.name, user_path(user), class: "user-name"
#user-overview
  .user-rp
    a #{user.recomme_point}RP
    a 「#{user.title.name}」
  - if user.genres.present?
    - user.genres.each do |genre|
      .genre-tag-mark.bg-warning
        a.fa.fa-tag
        = link_to genre.name, books_path(genre_id: genre.id), id: "genre-tag-text"
    

app/views/shared/_recently_recommend_book.html.slim
.card
  .card-header
    p 最近レコメブックスで
    p レコメンドされた本
  .card-body
    #book-thumb-image
      = link_to book_path(book)
        - if book.image?
          = image_tag book.image, class: "book-image", width: '140px'
        - else
          =image_tag 'booklogo.jpg', size: '120x135', class: "book-image"
    #book-thumb-overview
      = link_to book.title, book_path(book), class: "book-info title"
      .book-info.author
        = link_to book.author.name, author_path(book.author)
        a 著
      a.book-info.rep #{book.recomme_evaluation_point}REP

app/views/shared/_right_side.html.slim
.right-side
  - if !@recently_recommend_book.nil?
    .recently-recommend-book.table-bordered
      = render 'shared/recently_recommend_book', { book: @recently_recommend_book }
   
  .twitter.table-bordered
    <a class="twitter-timeline" data-lang="ja" data-width="255" data-height="600" data-theme="light" href="https://twitter.com/books06805400?ref_src=twsrc%5Etfw">Tweets by books06805400</a> 
    <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

app/views/shared/_right_side_for_login_signup.html.slim
.right-side
  - if !@recently_recommend_book.nil?
    .recently-recommend-book.table-bordered
      = render 'shared/recently_recommend_book', { book: @recently_recommend_book }
   
  .twitter.table-bordered
    <a class="twitter-timeline" data-lang="ja" data-width="255" data-height="600" data-theme="light" href="https://twitter.com/books06805400?ref_src=twsrc%5Etfw">Tweets by books06805400</a> 
    <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

app/views/shared/_right_side_for_mypage.html.slim
.right-side
  - if !@recently_recommend_book.nil?
    .recently-recommend-book.table-bordered
      = render 'shared/recently_recommend_book', { book: @recently_recommend_book }
   
  .twitter.table-bordered
    <a class="twitter-timeline" data-lang="ja" data-width="255" data-height="600" data-theme="light" href="https://twitter.com/books06805400?ref_src=twsrc%5Etfw">Tweets by books06805400</a> 
    <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>