config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    resources :relationships, only: [:create, :destroy]
    resources :recommends, only: :index
  end

  resources :recommends, only: [:new, :create, :update]
  namespace :recommends do
    resources :users, only: :index
    resources :books, only: :index
  end

  resources :books do
    get :search, on: :collection
    resource :favorites, only: [:create, :destroy]
    resource :reviews, only: [:create, :edit, :update, :destroy]
  end

  resources :authors, only: [:index, :show]

  resources :notifications, only: :index

end

app/models/recommend.rb
class Recommend < ApplicationRecord
    belongs_to :recommender, class_name: "User"
    belongs_to :recommended, class_name: "User"
    belongs_to :book
    validates :book_id, uniqueness: { scope: [:recommender_id, :recommended_id]  }
    validates :status, presence: true
    has_many :notifications, dependent: :destroy

    def create_notification_recommend!
        create_notification!('recommend')
    end

    def create_notification_response!
        create_notification!('response')
    end

    def create_notification!(action)
        notification = recommender.notifications.where(visited: recommended, recommend_id: id, action: action)
        if notification.blank?
            new_notification = self.recommended.active_notifications.new(visited_id: recommender_id, recommend_id: id, action: action)
            new_notification.save! if new_notification.valid?
        end
    end
end

app/controllers/recommends/books_controller.rb
class Recommends::BooksController < ApplicationController

    def index
        @q = Book.ransack(params[:q])
        @books = @q.result(distinct: true).paginate(page: params[:page])
        @user_id = params[:user_id] || params.dig(:q, :user_id)
    end
    
end

app/controllers/recommends/users_controller.rb
class Recommends::UsersController < ApplicationController

    def index
        @q = User.ransack(params[:q])
        @users = @q.result(distinct: true).order(created_at: "DESC").paginate(page: params[:page])
        @book_id = params[:book_id] || params.dig(:q, :book_id)
    end
    
end

app/controllers/recommends_controller.rb
class RecommendsController < ApplicationController

    before_action :logged_in_user

    def new
        @recommend = Recommend.new
        if params[:user_id]
            @user = User.find_by(id: params[:user_id])
        end
        if params[:book_id]
            @book = Book.find_by(id: params[:book_id])
        end
    end

    def create
        @recommend = Recommend.new(recommend_params)
        if @recommend.save
            @recommend.create_notification_recommend!
            flash[:primary] = "レコメンドが完了しました！"
            redirect_to user_recommends_path(current_user.id)
        else
            flash.now[:danger] = "レコメンドに失敗しました"
            render 'new'
        end
    end

    def index
        @user = User.find(params[:user_id])
        @active_recommends = @user.active_recommends.order(created_at: :desc).paginate(page: params[:page])
        @passive_recommends = @user.passive_recommends.order(created_at: :desc).paginate(page: params[:page])
        @for_passive = params[:for_passive]
    end

    def update
        recommend = Recommend.find(params[:id])
        if recommend.update_attributes(recommend_params)
            recommend.create_notification_response!
            if recommend.status == 2
                recommend.recommender.increment!(:recomme_point, 1)
                recommend.recommender.update_title_or_not
                recommend.book.increment!(:recomme_evaluation_point, 1)
            end
            flash[:primary] = "レコメンドに対する回答を完了しました！"
            redirect_to user_recommends_path(current_user.id, for_passive: true)
        else
            flash[:danger] = "回答に失敗しました"
            redirect_to user_recommends_path(current_user.id)
        end
    end

    private

        def recommend_params
            params.require(:recommend).permit(:recommender_id, :recommended_id, :book_id, :body, :status)
        end
end

app/helpers/recommends/books_helper.rb
module Recommends::BooksHelper
end

app/helpers/recommends/users_helper.rb
module Recommends::UsersHelper
end

app/views/recommends/_active_recommend_status.html.slim
- if recommend.status == 1
  .status.bulue
    i.far.fa-lightbulb
    a 回答まち
- else
  .status
    i.fas.fa-check-square
    a 回答あり

app/views/recommends/_my_active_recommend.html.slim
div class="my-active-recommend card #{recommend.status == 1 ? 'border-primary' : ''}"
  .card-header
    .row
      .col-xl-7
        - if recommend.recommended.image?
          = image_tag recommend.recommended.image_url(:thumb3), class: "user-image"
        - else
          = image_tag 'userlogo2.png', size: '30x30', class: "user-image"
        = link_to recommend.recommended.name, user_path(recommend.recommended), class: "user-name"
        a さんへのレコメンド
      .col-xl-5
        #recommend-status
          = render 'recommends/active_recommend_status', { recommend: recommend }
  .card-body
    .row
      .col-xl-3
        #book-thumb-image
          = link_to book_path(recommend.book)
            - if recommend.book.image?
              = image_tag recommend.book.image, class: "book-image", height: '200px'
            - else
              =image_tag 'booklogo.jpg', class: "book-image", height: '200px'
      .col-xl-8
        p.book-title
          = link_to recommend.book.title, book_path(recommend.book)
        p.book-author
          = link_to recommend.book.author.name, author_path(recommend.book.author)
          a 著
        #recommend-body
          - if recommend.body?
            p.heading アピール文
            .reco-apeal.table-bordered
              = safe_join(recommend.body.split("\n"), tag(:br))
      .col-xl-1
  - if recommend.status == 2
    .card-footer
      p.status 回答「面白かった！」
  - elsif recommend.status == 3
    .card-footer
      p.status 回答「合わなかったかも」
  - elsif recommend.status == 4
    .card-footer
      p.status 回答「読んだことがある」

app/views/recommends/_my_passive_recommend.html.slim
div class="my-passive-recommend card #{recommend.status == 1 ? 'border-primary' : ''}"
  .card-header
    .row
      .col-xl-7
        - if recommend.recommender.image?
          = image_tag recommend.recommender.image_url(:thumb3), class: "user-image"
        - else
          = image_tag 'userlogo2.png', size: '30x30', class: "user-image"
        = link_to recommend.recommender.name, user_path(recommend.recommender), class: "user-name"
        a さんからのレコメンド
      .col-xl-5
        #recommend-status
          = render 'recommends/passive_recommend_status', { recommend: recommend }
  .card-body
    .row
      .col-xl-3
        #book-thumb-image
          = link_to book_path(recommend.book)
            - if recommend.book.image?
              = image_tag recommend.book.image, class: "book-image", height: '200px'
            - else
              =image_tag 'booklogo.jpg', class: "book-image", height: '200px'
      .col-xl-8
        p.book-title
          = link_to recommend.book.title, book_path(recommend.book)
        p.book-author
          = link_to recommend.book.author.name, author_path(recommend.book.author)
          a 著
        - if recommend.status == 1
          div id = "favorite-button-#{recommend.book.id}" class = "favorite"
            = render 'favorites/favorite', book: recommend.book
        #recommend-body
          - if recommend.body?
            p.heading アピール文
            .reco-apeal.table-bordered
              = safe_join(recommend.body.split("\n"), tag(:br))
      .col-xl-1
  - if recommend.status == 1
    .card-footer
      .suggest ３つの選択肢からレコメンドに対する回答をしてください
      = form_with model: recommend, local: true do |f|
        = f.hidden_field :status, :value => 2
        = f.submit '1. 面白かった！', class: 'btn btn-primary btn-block'
      = form_with model: recommend, local: true do |f|
        = f.hidden_field :status, :value => 3
        = f.submit '2. 合わなかったかも', class: 'btn i3 btn-block'
      = form_with model: recommend, local: true do |f|
        = f.hidden_field :status, :value => 4
        = f.submit '3. 読んだことがある', class: 'btn i4 btn-block'
  - elsif recommend.status == 2
    .card-footer
      p.status あなたの回答「面白かった！」
  - elsif recommend.status == 3
    .card-footer
      p.status あなたの回答「合わなかったかも」
  - elsif recommend.status == 4
    .card-footer
      p.status あなたの回答「読んだことがある」

app/views/recommends/_passive_recommend_status.html.slim
- if recommend.status == 1
  .status.bulue
    i.far.fa-lightbulb
    a 未回答
- else
  .status
    i.fas.fa-check-square
    a 回答済み

app/views/recommends/_user_active_recommend.html.slim
.user-active-recommend.card
  .row
    .col-xl-3
      #book-thumb-image
        = link_to book_path(recommend.book)
          - if recommend.book.image?
            = image_tag recommend.book.image, class: "book-image", height: '200px'
          - else
            =image_tag 'booklogo.jpg', class: "book-image", height: '200px'
    .col-xl-8
      p.book-title
        = link_to recommend.book.title, book_path(recommend.book)
      p.book-author
        = link_to recommend.book.author.name, author_path(recommend.book.author)
        a 著
    .col-xl-1

app/views/recommends/_user_passive_recommend.html.slim
.user-passive-recommend.card
  .row
    .col-xl-3
      #book-thumb-image
        = link_to book_path(recommend.book)
          - if recommend.book.image?
            = image_tag recommend.book.image, class: "book-image", height: '200px'
          - else
            =image_tag 'booklogo.jpg', class: "book-image", height: '200px'
    .col-xl-8
      p.book-title
        = link_to recommend.book.title, book_path(recommend.book)
      p.book-author
        = link_to recommend.book.author.name, author_path(recommend.book.author)
        a 著
    .col-xl-1

app/views/recommends/index.html.slim
- provide(:title, "レコメンド状況")
  - if current_user?(@user)
    - breadcrumb :my_recomme_index, @user
  - else
    - breadcrumb :user_recomme_index, @user
.container
  == breadcrumbs separator:  ">" , class: "breadcrumb"
  
  .row
    .col-xl-9#reco-index
      - if current_user?(@user)
        h2 あなたのレコメンド状況
      - else
        h2 #{@user.name}さんのレコメンド状況
      ul.nav.nav-tabs.justify-content-center role = "tablist"         
        li.nav-item
          a class="nav-link #{@for_passive.nil? ? 'active' : ''}" id="active-reco-tab" data-toggle="tab" href="#active-reco" role="tab" aria-controls="active-reco" aria-selected="true"
            p レコメンドした本
        li.nav-item
          a class="nav-link #{@for_passive.nil? ? '' : 'active'}" id="passive-reco-tab" data-toggle="tab" href="#passive-reco" role="tab" aria-controls="passive-reco" aria-selected="false"
            p レコメンドされた本
      .tab-content
        div class="tab-pane fade #{@for_passive.nil? ? 'active show' : ''}" id="active-reco" role="tabpanel" aria-labelledby="active-reco-tab"
          - if @active_recommends.present?
            - @active_recommends.each do |active_recommend|
              - if current_user?(@user)
                = render 'recommends/my_active_recommend', { recommend: active_recommend }
              - else
                = render 'recommends/user_active_recommend', { recommend: active_recommend }
            = will_paginate(@active_recommends, renderer: WillPaginate::ActionView::BootstrapLinkRenderer)
          - else
            p 表示するレコメンドがありません
        div class="tab-pane fade #{@for_passive.nil? ? '' : 'active show'}" id="passive-reco" role="tabpanel" aria-labelledby="passive-reco-tab"
          - if @passive_recommends.present?
            - @passive_recommends.each do |passive_recommend|
              - if current_user?(@user)
                = render 'recommends/my_passive_recommend', { recommend: passive_recommend }
              - else
                = render 'recommends/user_passive_recommend', { recommend: passive_recommend }
            = will_paginate(@passive_recommends, renderer: WillPaginate::ActionView::BootstrapLinkRenderer)
          - else
            p 表示するレコメンドがありません




    .col-xl-3
      = render 'shared/right_side'

app/views/recommends/new.html.slim
- provide(:title, "レコメンド")
- breadcrumb :recommend
.container
  == breadcrumbs separator:  ">" , class: "breadcrumb"
  
  .row
    .col-xl-9#recommend
      .col-xl-11
        h2 レコメンド
        p.reco-intro レコメンドする本とユーザーを選んでください
      .col-xl-1
      .row
        .col-lg-3.reco-current
          #current-user-thumb-image
            - if current_user.image?
              = image_tag current_user.image_url(:thumb1), class: "user-image", height: '200px'
            - else
              =image_tag 'userlogo2.png', class: "user-image", height: '200px'
            h4 あなた
        .col-lg-1.arrow-space.left.fa-3x
          .fa.fa-arrow-right.d-none.d-lg-block
        .col-lg-3.reco-book
          - if !@book.present? && @user.present?
            = link_to 'レコメンドする本を選ぶ', recommends_books_path(user_id: @user.id), class: "btn btn-primary", id: "reco-book-btn"
          - elsif !@book.present? && !@user.present?
            = link_to 'レコメンドする本を選ぶ', recommends_books_path, class: "btn btn-primary", id: "reco-book-btn"
          
          - if @book.present?
            #book-thumb-image
              - if @book.image?
                = image_tag @book.image, class: "book-image", height: '200px', id: "reco-book-image"
              - else
                =image_tag 'booklogo.jpg', class: "book-image", height: '200px', id: "reco-book-image"
            h4  #{@book.title}
            - if @user.present?
              = link_to '本を変更', recommends_books_path(user_id: @user.id), class: "btn-primary btn rechose"
            - elsif !@user.present?
              = link_to '本を変更', recommends_books_path, class: "btn-primary btn rechose"
        .col-lg-1.arrow-space.right
          .fa.fa-arrow-right.fa-3x.d-none.d-lg-block
        .col-lg-3.reco-user
          - if !@user.present? && @book.present?
            = link_to recommends_users_path(book_id: @book.id), class: "btn btn-primary", id: "reco-user-btn" do
              span レコメンドする
              br
              span ユーザーを選ぶ
          - elsif !@user.present? && !@book.present?
            = link_to recommends_users_path, class: "btn btn-primary", id: "reco-user-btn" do
              span レコメンドする
              br
              span ユーザーを選ぶ
          - if @user.present?
            #users-thumb-image
              - if @user.image?
                = image_tag @user.image_url(:thumb1), class: "user-image", height: '200px'
              - else
                =image_tag 'userlogo2.png', class: "user-image", height: '200px'
              h4 #{@user.name}さん
            - if @book.present?
              = link_to 'ユーザーを変更', recommends_users_path(book_id: @book.id), class: "btn-primary btn rechose"
            - elsif !@book.present?
              = link_to 'ユーザーを変更', recommends_users_path, class: "btn-primary btn rechose"
        .col-lg-1
      .row.reco-message-area
        .col-xl-4
        .col-xl-7.reco-message
          - if @user.present? && @book.present?
            - if !Recommend.find_by(recommended_id: @user.id, book_id: @book.id).nil?
              .alert-area
                p.alert 「#{@user.name}」さんはすでに「#{@book.title}」のレコメンドを受けております。
                p.alert 本かユーザーを選びなおしてください。
            - elsif !Recommend.find_by(recommender_id: @user.id, book_id: @book.id).nil?
              .alert-area
                p.alert 「#{@book.title}」は「#{@user.name}」さんがレコメンドしたことのある本です。
                p.alert 本かユーザーを選びなおしてください。
            - elsif !Book.find_by(id: @book.id, user_id: @user.id).nil?
              .alert-area
                p.alert 「#{@book.title}」は「#{@user.name}」さんが投稿した本です。
                p.alert 本かユーザーを選びなおしてください。
            - else
              .row#chose-message-line
              = form_with model: @recommend, local: true do |f|
                = render 'shared/error_messages', object: f.object
                .form-group
                  = f.hidden_field :recommender_id, :value => current_user.id
                  = f.hidden_field :recommended_id, :value => @user.id
                  = f.hidden_field :book_id, :value => @book.id
                  
                  = f.label :body, 'アピール文'
                  = f.text_area :body, class: 'form-control', id: 'reco-message-field'

                  = button_tag type: 'submit', class: 'btn-block btn btn-primary' do
                    i.fas.fa-hand-holding-heart
                    span レコメンドする
        .col-xl-1


    .col-xl-3
      = render 'shared/right_side'
          